apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: mgr
spec:
  name: .mgr
  failureDomain: host
  replicated:
    requireSafeReplicaSize: false
    size: 1
  # Enables collecting RBD per-image IO statistics by enabling dynamic OSD performance counters. Defaults to false.
  # For reference: https://docs.ceph.com/docs/latest/mgr/prometheus/#rbd-io-statistics
  # enableRBDStats: true
