apiVersion: v1
kind: PersistentVolume
metadata:
  name: rook-ceph-local-path-data
spec:
  capacity:
    storage: 10Gi
  volumeMode: Block
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    # path: /var/lib/rook/local-path-data
    path: /dev/loop23p1
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          # Single-node "cluster" setup, so we can use the hostname of the node where the mon pod is scheduled.
          - key: kubernetes.io/hostname
            operator: Exists
